import "./globals.css";
import type { Metadata } from "next";
import { Inter, Manrope, Roboto } from "next/font/google";
import { Header } from "@/components/Header/Header";
import { Providers } from "@/components/Providers";

const inter = Inter({ subsets: ["latin"] });
const manrope = Manrope({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={manrope.className}>
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
